"""initial_schema

Revision ID: 788e35600694
Revises: d00287650a8c
"""
import sqlalchemy as sa
from alembic import op


revision = '788e35600694'
down_revision = 'd00287650a8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
