"""initial_schema

Revision ID: d00287650a8c
Revises: 
"""
import sqlalchemy as sa
from alembic import op


revision = 'd00287650a8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'chave')
    )
    op.create_index(op.f('ix_configuracoes_empresa_id'), 'configuracoes', ['empresa_id'], unique=False)
    op.create_table('regras_reincidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero_ocorrencia', sa.Integer(), nullable=False),
    sa.Column('consequencia', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero_ocorrencia')
    )
    op.create_index(op.f('ix_regras_reincidencia_empresa_id'), 'regras_reincidencia', ['empresa_id'], unique=False)
    op.create_table('tipos_ocorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_ocorrencia_empresa_id'), 'tipos_ocorrencia', ['empresa_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMIN', 'MOTORISTA', 'RESPONSAVEL', name='perfil', native_enum=False, length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('apelido', sa.String(length=60), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'placa')
    )
    op.create_index(op.f('ix_veiculos_empresa_id'), 'veiculos', ['empresa_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_motoristas_empresa_id'), 'motoristas', ['empresa_id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_usuario_id'), 'notificacoes', ['usuario_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('responsaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_responsaveis_empresa_id'), 'responsaveis', ['empresa_id'], unique=False)
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('escola', sa.String(length=120), nullable=False),
    sa.Column('serie', sa.String(length=40), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_empresa_id'), 'alunos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_alunos_responsavel_id'), 'alunos', ['responsavel_id'], unique=False)
    op.create_table('rotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('escola', sa.String(length=120), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ATIVA', 'INATIVA', name='statusrota', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rotas_empresa_id'), 'rotas', ['empresa_id'], unique=False)
    op.create_table('frequencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENTE', 'FALTA', name='statusfrequencia', native_enum=False, length=20), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'data')
    )
    op.create_index(op.f('ix_frequencias_aluno_id'), 'frequencias', ['aluno_id'], unique=False)
    op.create_table('historico_rotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('EM_ANDAMENTO', 'FINALIZADA', name='statusexecucao', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['rota_id'], ['rotas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_rotas_rota_id'), 'historico_rotas', ['rota_id'], unique=False)
    op.create_table('mensalidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'ATRASADO', 'CANCELADO', name='statusmensalidade', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensalidades_aluno_id'), 'mensalidades', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_mensalidades_empresa_id'), 'mensalidades', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_mensalidades_responsavel_id'), 'mensalidades', ['responsavel_id'], unique=False)
    op.create_table('ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('gravidade', sa.Enum('LEVE', 'MEDIA', 'GRAVE', name='gravidade', native_enum=False, length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('consequencia', sa.String(length=120), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocorrencias_aluno_id'), 'ocorrencias', ['aluno_id'], unique=False)
    op.create_table('paradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rota_id'], ['rotas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rota_id', 'ordem')
    )
    op.create_index(op.f('ix_paradas_rota_id'), 'paradas', ['rota_id'], unique=False)
    op.create_table('localizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('historico_rota_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('velocidade', sa.Float(), nullable=True),
    sa.Column('direcao', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['historico_rota_id'], ['historico_rotas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_localizacoes_veiculo_ts', 'localizacoes', ['veiculo_id', 'timestamp'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensalidade_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('comprovante', sa.String(length=255), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mensalidade_id'], ['mensalidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_mensalidade_id'), 'pagamentos', ['mensalidade_id'], unique=False)
    op.create_table('rota_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('parada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['parada_id'], ['paradas.id'], ),
    sa.ForeignKeyConstraint(['rota_id'], ['rotas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rota_id', 'aluno_id')
    )
    op.create_index(op.f('ix_rota_alunos_aluno_id'), 'rota_alunos', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_rota_alunos_rota_id'), 'rota_alunos', ['rota_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rota_alunos_rota_id'), table_name='rota_alunos')
    op.drop_index(op.f('ix_rota_alunos_aluno_id'), table_name='rota_alunos')
    op.drop_table('rota_alunos')
    op.drop_index(op.f('ix_pagamentos_mensalidade_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index('ix_localizacoes_veiculo_ts', table_name='localizacoes')
    op.drop_table('localizacoes')
    op.drop_index(op.f('ix_paradas_rota_id'), table_name='paradas')
    op.drop_table('paradas')
    op.drop_index(op.f('ix_ocorrencias_aluno_id'), table_name='ocorrencias')
    op.drop_table('ocorrencias')
    op.drop_index(op.f('ix_mensalidades_responsavel_id'), table_name='mensalidades')
    op.drop_index(op.f('ix_mensalidades_empresa_id'), table_name='mensalidades')
    op.drop_index(op.f('ix_mensalidades_aluno_id'), table_name='mensalidades')
    op.drop_table('mensalidades')
    op.drop_index(op.f('ix_historico_rotas_rota_id'), table_name='historico_rotas')
    op.drop_table('historico_rotas')
    op.drop_index(op.f('ix_frequencias_aluno_id'), table_name='frequencias')
    op.drop_table('frequencias')
    op.drop_index(op.f('ix_rotas_empresa_id'), table_name='rotas')
    op.drop_table('rotas')
    op.drop_index(op.f('ix_alunos_responsavel_id'), table_name='alunos')
    op.drop_index(op.f('ix_alunos_empresa_id'), table_name='alunos')
    op.drop_table('alunos')
    op.drop_index(op.f('ix_responsaveis_empresa_id'), table_name='responsaveis')
    op.drop_table('responsaveis')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notificacoes_usuario_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_motoristas_empresa_id'), table_name='motoristas')
    op.drop_table('motoristas')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_veiculos_empresa_id'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_ocorrencia_empresa_id'), table_name='tipos_ocorrencia')
    op.drop_table('tipos_ocorrencia')
    op.drop_index(op.f('ix_regras_reincidencia_empresa_id'), table_name='regras_reincidencia')
    op.drop_table('regras_reincidencia')
    op.drop_index(op.f('ix_configuracoes_empresa_id'), table_name='configuracoes')
    op.drop_table('configuracoes')
    op.drop_table('empresas')
    # ### end Alembic commands ###
